name: cbc
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - fftw
  - h5py
  - hdf5plugin
  - llvm-openmp
  - numpy
  - pandas
  - pygmo
  - pytables
  - python=3.7
  - scipy
  - scikit-learn
  - tqdm