name: cbc
channels:
  - conda-forge
  - defaults
dependencies:
  - cython
  - gcc_linux-64
  - fftw
  - furo
  - h5py
  - hdf5plugin
  - llvm-openmp
  - mock
  - numpy
  - pillow
  - pip
  - pandas
  - pygmo
  - pytables
  - python=3.7
  - scikit-learn
  - scipy
  - sphinx
  - sphinx-autoapi
  - sphinx-toolbox
  - tqdm